warm:
  - 'red'
  - 'gold'
  - 'peru'
  - 'orangered'
  - 'tomato'
  - 'coral'
  - 'salmon'
  - 'crimson'
  - 'firebrick'
  - 'darkorange'
  - 'orange'
  - 'goldenrod'
  - 'darkgoldenrod'
  - 'lightcoral'
  - 'lightsalmon'
  - 'darksalmon'
  - 'indianred'
  - 'chocolate'
  - 'sienna'
  - 'saddlebrown'
  - 'brown'
  - 'maroon'
  - 'darkred'
  - 'peachpuff'
  - 'moccasin'
  - 'bisque'
  - 'navajowhite'
  - 'wheat'
  - 'pink'
  - 'hotpink'

cool:
  - 'forestgreen'
  - 'cyan'
  - 'darkviolet'
  - 'teal'
  - 'deepskyblue'
  - 'dodgerblue'
  - 'royalblue'
  - 'slateblue'
  - 'mediumseagreen'
  - 'turquoise'
  - 'green'
  - 'darkgreen'
  - 'seagreen'
  - 'darkseagreen'
  - 'mediumaquamarine'
  - 'aquamarine'
  - 'lightseagreen'
  - 'darkcyan'
  - 'cadetblue'
  - 'steelblue'
  - 'skyblue'
  - 'lightskyblue'
  - 'cornflowerblue'
  - 'blue'
  - 'mediumblue'
  - 'darkblue'
  - 'navy'
  - 'mediumslateblue'
  - 'indigo'
  - 'blueviolet'
  - 'mediumpurple'
  - 'mediumorchid'
  - 'orchid'
  - 'purple'