#file: noinspection YAMLSchemaValidation
env_id: 'deep-sea-treasure-concave-v0'
frame_dir: 'plots/sketches/dst_frame_abstr.png'
ref_point: [0, -50]
file_prefix: 'dst'
actions:
  0: 'up'
  1: 'down'
  2: 'left'
  3: 'right'
action_mapping:
  0: [-1, 0]
  1: [1, 0]
  2: [0, -1]
  3: [0, 1]
reward_dim: (2,)
observations_features: [ 'y', 'x' ]
obs_high: [ 11, 11 ]
obs_low: [ 0, 0 ]
gamma: 1.0
num_steps: 50
tolerance: 0
eval_episodes: 1
nadir: [0,-50]
ideal: [124,0]