#file: noinspection YAMLSchemaValidation
env_id: 'minecart-v0'
ref_point: [-1.0, -1.0, -200.0]
file_prefix: 'minetrain'
actions:
  0: 'Mine'
  1: 'Left'
  2: 'Right'
  3: 'Accelerate'
  4: 'Brake'
  5: 'None'
reward_dim: (3,)
observations_features: ['x', 'y', 'speed', 'sin', 'cos', 'ore1load', 'ore2load']
observations_high: [1., 1., 1., 1., 1., 1., 1.]
observations_low: [-1., -1., -1., -1., -1., -1., -1.]
gamma: 1.
num_steps: 1000
tolerance: 1e-15
eval_episodes: 100
extrema: ([0., 0., -200.], [1.5, 1.5, 0.])
quant_bins: [100, 100, 6, 10, 10, 90, 90]